apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymusicstats-deployment
  labels:
    app: mymusicstats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymusicstats
  template:
    metadata:
      labels:
        app: mymusicstats
    spec:
      containers:
      - name: mymusicstats
        image: vedaangss/my-web-app:v2
        ports:
        - containerPort: 80
